packages:
  - packages/*
  - services/*

catalogs:
  core:
    "@types/events": "^3.0.3"
    "@types/uuid": "^11.0.0"
    "@types/ws": "^8.18.1"
    "nodemon": "^3.1.14"
    "ts-node": "^10.9.2"
    "typescript": "^5.9.3"
    "events": "^3.3.0"
    "http": "0.0.1-security"
    "uuid": "^13.0.0"
    "ws": "^8.19.0"
